[package]
name = "komari-monitor-rs"
version = "0.3.4"
edition = "2024"
authors = ["GenshinMinecrat <gm@highp.ing>"]
description = "Komari Monitor Agent in Rust"
repository = "https://github.com/GenshinMinecraft/ak_monitor_client_rs"
license = "WTFPL"

[dependencies]
log = { version = "0.4", default-features = false, features = ["std"] }
simple_logger = { version = "5", features = ["stderr", "time", "colored"] }
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "macros", "time", "process", "sync", "net", "fs"] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
rustls-pki-types = "1"
futures = { version = "0.3", default-features = false, features = ["std"] }
miniserde = { version = "0.1", default-features = false, features = ["std"] }
tokio-tungstenite = { version = "0.28.0", default-features = false, features = ["rustls-tls-webpki-roots", "connect"] }
palc = { version = "0.0.2", default-features = false, features = ["help"] }
sysinfo = { version = "0.37.2", default-features = false, features = ["disk", "system", "multithread", "network"] }
time = { version = "0.3.44", default-features = false, features = ["local-offset", "formatting"] }
icmp-socket = "0.2.0"
portable-pty = "0.9.0"
url = { version = "2.5.7", default-features = false, features = ["std"] }

ureq = { version = "3.1", default-features = false, features = ["gzip", "rustls"], optional = true }
nyquest = { version = "0.4.0", default-features = false, features = ["blocking"], optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
raw-cpuid = "11.5.0"
netstat2 = "0.11.2"
win-toast-notify = "0.1.6"

[target.'cfg(not(target_os = "linux"))'.dependencies]
nyquest-preset = { version = "0.3", default-features = false, features = ["blocking"], optional = true }

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
libc = "0.2.175"

[target.'cfg(target_os = "linux")'.dependencies]
heim-virt = "0.1.0-alpha.1"
nyquest-backend-curl = { version = "0.3.1", default-features = false, features = ["blocking"], optional = true }
curl = { version = "0.4.49", default-features = false, optional = true }
rustls-ffi = { version = "0.15.0", default-features = false, features = ["ring"], optional = true }

[target.'cfg(target_os = "windows")'.build-dependencies]
thunk-rs = { version = "0.3.5", features = ["xp"], default-features = false, optional = true }

[features]
ureq-support = ["ureq"]
nyquest-support = ["nyquest", "nyquest-backend-curl", "curl", "nyquest-preset", "rustls-ffi"]
winxp-support = ["thunk-rs"]

# Default Dev Profile
[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

# Default Release Profile
[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false

[profile]
minimal = { inherits = "release", opt-level = "z", lto = true, codegen-units = 1, panic = "abort", debug = false, strip = true, debug-assertions = false, overflow-checks = false }
